kind: Secret
apiVersion: v1
metadata:
  name: cosign-secret
data:
  cosign.key: "{{ $.Values.globex.cosign.privateKey }}"
  cosign.password: "{{ $.Values.globex.cosign.password }}"
  cosign.pub: "{{ $.Values.globex.cosign.publicKey }}"
type: Opaque
