apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: globex-unsigned
  namespace: openshift-gitops
spec:
  destination:
    namespace: "{{ $.Values.development.globex-unsigned.namespace }}"
    server: 'https://kubernetes.default.svc'
  project: default
  ignoreDifferences:
    - group: '*'
      jqPathExpressions:
        - '.imagePullSecrets[] | select(.name|test(".-dockercfg-."))'
      kind: ServiceAccount
  source:
    path: "{{ $.Values.development.globex-unsigned.contextDir }}"
    repoURL: "{{ $.Values.development.repoUrl }}"
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - RespectIgnoreDifferences=true
    - CreateNamespace=true