kind: Secret
apiVersion: v1
metadata:
  name: config-bundle
stringData:
  config.yaml: |-
    REGISTRY_TITLE: Red Hat Product Demo System Quay
    SERVER_HOSTNAME: {{ _quay_host_name }}
    EXTERNAL_TLS_TERMINATION: true
    SUPER_USERS:
    - quayadmin
    FEATURE_USER_INITIALIZE: true
type: Opaque
